### ISSUE TITLE
Iris does not work properly when using Zeph

### ISSUE THREAD

**Issue by DD152** [dioptra-io/iris#165]
[zeph issues#29](https://github.com/dioptra-io/zeph/issues/29)

**Comment by DD152** [comment]
In  agent container, I try ```tshark -i eth0 -f'icmp'``` and run zeph
```zeph t.txt --iris-base-url http://api.docker.localhost --iris-username admin@example.org --iris-password admin```

t.txt like this:

> 164.52.9.0/24
23.220.175.0/24

but tshark capture nothing. Agent doesn't seem to be working.
Then , I run
``` ping 164.52.9.69```

> PING 164.52.9.69 (164.52.9.69) 56(84) bytes of data.
64 bytes from 164.52.9.69: icmp_seq=1 ttl=53 time=253 ms

```traceroute -n 164.52.9.69```

> traceroute to 164.52.9.69 (164.52.9.69), 30 hops max, 60 byte packets
 1  172.18.0.1  0.038 ms  0.009 ms  0.012 ms
 2  148.153.115.57  0.366 ms  0.317 ms  0.325 ms
 3  * * *
 4  38.123.105.164  1.062 ms 148.153.233.101  0.656 ms 148.153.233.103  1.041 ms
 5  212.162.44.197  0.915 ms 193.251.254.215  2.454 ms 154.14.67.121  0.924 ms
 6  154.54.56.189  1.063 ms  1.095 ms  1.095 ms
 7  193.251.247.206  1.279 ms 195.2.20.225  1.045 ms 63.218.231.17  1.115 ms
 8  154.54.72.110  21.624 ms *  21.279 ms
 9  * 154.54.0.42  175.394 ms  175.431 ms
10  154.54.40.138  197.214 ms  197.052 ms  196.991 ms
11  * * *
12  * * 203.75.229.101  297.400 ms
13  113.21.95.72  249.789 ms * *
14  113.21.85.242  202.905 ms *  202.739 ms
15  113.21.85.242  251.998 ms  251.948 ms  252.362 ms
16  * 164.52.69.6  254.383 ms  251.882 ms

**Comment by matthieugouel** [comment]
Hey again! Thanks for sticking with it. 
Did you try to create a simple measurement manually with Iris API? The doc may help you with that: https://dioptra-io.github.io/iris/api/. The simplest way is to use the swagger located in http(s)://<api-url>/docs.
Maybe there is an issue with the configuration of the agent that prevent it to probe, even though it as access to the network.

**Comment by matthieugouel** [comment]
Pinging @SaiedKazemi @hrimlinger

**Comment by SaiedKazemi** [comment]
@matthieugouel Thank you for pinging me and @hrimlinger.  I will look into this today.

**Comment by DD152** [comment]
> Hey again! Thanks for sticking with it. Did you try to create a simple measurement manually with Iris API? The doc may help you with that: https://dioptra-io.github.io/iris/api/. The simplest way is to use the swagger located in `http(s)://<api-url>/docs`. Maybe there is an issue with the configuration of the agent that prevent it to probe, even though it as access to the network.
> 
> To do a manual measurement with the swagger, first log into it with your Iris credential (with the authorize button) then, upload a small target list (see https://dioptra-io.github.io/iris/concepts/) and then launch a measurement (for instance a yarrp one using your target list)

I dont have linux GUI, so I submit measurement by python, like:
```
from iris_client import IrisClient
with IrisClient(
        base_url='http://api.docker.localhost',
        username='admin@example.org',
        password='admin',
) as iris:
    request_body={
        "tool": "yarrp",
        "agents": [
            {
                "tag": "all",
                "target_file": "prefixes.csv"
            }
        ],
        "tags": [
            "test"
        ]
    }
    res = iris.post("/measurements", json=request_body).json()
    print(res)
```
but, I receive 

> {'detail': 'Target file not found'}

So, where should I put the target_files in operating system?

**Comment by SaiedKazemi** [comment]
@DD152 Did you upload your target file and, if so, did you call it `prefixes.csv`?  Each measurement needs a target file that should first be uploaded and then referenced in the request to run the measurement.

Regarding `I don't have linux GUI`, your browser doesn't have to necessarily run on Linux.  It can run on Windows or MacOS.  If you use a browser, it will be a lot easier to upload your target list, post a request to run a measurement, get the status of your measurement, etc.  But of course you can also use the command line if that's your preferred method.

**Comment by DD152** [comment]
> @DD152 Did you upload your target file and, if so, did you call it `prefixes.csv`? Each measurement needs a target file that should first be uploaded and then referenced in the request to run the measurement.
> 
> Regarding `I don't have linux GUI`, your browser doesn't have to necessarily run on Linux. It can run on Windows or MacOS. If you use a browser, it will be a lot easier to upload your target list, post a request to run a measurement, get the status of your measurement, etc. But of course you can also use the command line if that's your preferred method.

Thank you for your patience! In addition, I found that if you want to access API externally, you need to modify the `docker-compose.yml`：

>  api:
           ...
           ports:
           - "8000:8000"
           ...

Then, you could access API web by visiting `http//:IP:8000`.

I successfully uploaded target file `t.csv`:

> {
  "key": "t.csv",
  "size": 53,
  "content": [],
  "last_modified": "2023-11-29T02:38:16+00:00"
}

 `t.csv` has two /24:

> 164.52.9.0/24,icmp,2,20,6
23.220.175.0/24,icmp,1,20,6

And request a measurement：

> {
  "tool": "yarrp",
  "tags": [
    "test"
  ],
  "uuid": "ab989b66-a4d8-4365-aa65-6c89f9536136",
  "user_id": "fb2ebc52-7685-41cc-926a-880e6a939ee2",
  "creation_time": "2023-11-29T02:43:26.980473",
  "start_time": null,
  "end_time": null,
  "state": "created",
  "agents": [
    {
      "tool_parameters": {
        "initial_source_port": 24000,
        "destination_port": 33434,
        "max_round": 10,
        "failure_probability": 0.05,
        "flow_mapper": "RandomFlowMapper",
        "flow_mapper_kwargs": {
          "seed": 42
        },
        "prefix_len_v4": 24,
        "prefix_len_v6": 64,
        "global_min_ttl": 1,
        "global_max_ttl": 20
      },
      "batch_size": null,
      "probing_rate": null,
      "target_file": "t.csv",
      "agent_uuid": "2bea48fd-2349-44aa-badd-daeb13c497f8",
      "agent_parameters": {
        "version": "1.1.2",
        "hostname": "3a99dcf487c1",
        "internal_ipv4_address": "172.18.0.7",
        "internal_ipv6_address": null,
        "external_ipv4_address": null,
        "external_ipv6_address": null,
        "cpus": 4,
        "disk": 121.407,
        "memory": 7.62,
        "min_ttl": 5,
        "max_probing_rate": 1000,
        "tags": [
          "all"
        ]
      },
      "probing_statistics": {},
      "state": "created"
    }
  ]
}

I get this measurement, and "state" is **ALWAYS** "ongoing":
> {
      "tool": "yarrp",
      "tags": [
        "test"
      ],
      "uuid": "ab989b66-a4d8-4365-aa65-6c89f9536136",
      "user_id": "fb2ebc52-7685-41cc-926a-880e6a939ee2",
      "creation_time": "2023-11-29T02:43:26.980473",
      "start_time": "2023-11-29T02:43:27.600119",
      "end_time": null,
      **"state": "ongoing",**
      "agents": [
        {
          "agent_uuid": "2bea48fd-2349-44aa-badd-daeb13c497f8"
        }
      ]
    }


Meanwhile, the agent status is idle:
>{
  "count": 1,
  "next": null,
  "previous": null,
  "results": [
    {
      "uuid": "2bea48fd-2349-44aa-badd-daeb13c497f8",
      **"state": "idle",**
      "parameters": {
        "version": "1.1.2",
        "hostname": "3a99dcf487c1",
        "internal_ipv4_address": "172.18.0.7",
        "internal_ipv6_address": null,
        "external_ipv4_address": null,
        "external_ipv6_address": null,
        "cpus": 4,
        "disk": 121.407,
        "memory": 7.62,
        "min_ttl": 5,
        "max_probing_rate": 1000,
        "tags": [
          "all"
        ]
      }
    }
  ]
}

clickhouse has results table, but the table is null. Then I cancel the measurement by api:

> {
  "tool": "yarrp",
  "tags": [
    "test"
  ],
  "uuid": "ab989b66-a4d8-4365-aa65-6c89f9536136",
  "user_id": "fb2ebc52-7685-41cc-926a-880e6a939ee2",
  "creation_time": "2023-11-29T02:43:26.980473",
  "start_time": "2023-11-29T02:43:27.600119",
  "end_time": "2023-11-29T09:01:17.620127",
  "state": "canceled",
  "agents": [
    {
      "tool_parameters": {
        "initial_source_port": 24000,
        "destination_port": 33434,
        "max_round": 10,
        "failure_probability": 0.05,
        "flow_mapper": "RandomFlowMapper",
        "flow_mapper_kwargs": {
          "seed": 42
        },
        "prefix_len_v4": 24,
        "prefix_len_v6": 64,
        "global_min_ttl": 1,
        "global_max_ttl": 20
      },
      "batch_size": null,
      "probing_rate": null,
      "target_file": "t.csv",
      "agent_uuid": "2bea48fd-2349-44aa-badd-daeb13c497f8",
      "agent_parameters": {
        "version": "1.1.2",
        "hostname": "3a99dcf487c1",
        "internal_ipv4_address": "172.18.0.7",
        "internal_ipv6_address": null,
        "external_ipv4_address": null,
        "external_ipv6_address": null,
        "cpus": 4,
        "disk": 121.407,
        "memory": 7.62,
        "min_ttl": 5,
        "max_probing_rate": 1000,
        "tags": [
          "all"
        ]
      },
      "probing_statistics": {
        "1:10:0": {
          "round": {
            "limit": 10,
            "number": 1,
            "offset": 0
          },
          "end_time": "2023-11-29T02:43:30.586162",
          "start_time": "2023-11-29T02:43:30.491122",
          "probes_read": 0,
          **"packets_sent": 0,**
          "pcap_dropped": 0,
          "pcap_received": 0,
          "packets_failed": 0,
          "filtered_low_ttl": 0,
          "packets_received": 0,
          "filtered_high_ttl": 0,
          "filtered_prefix_excl": 0,
          "pcap_interface_dropped": 0,
          "filtered_prefix_not_incl": 0,
          "packets_received_invalid": 0
        }
      },
      "state": "canceled"
    }
  ]
}

My question is: Why is there **"packets_sent": 0,** in the above response? Where should I check to generate data in clickhouse?

**Comment by SaiedKazemi** [comment]
Thank you @DD152 for all the information you have provided and sorry that you are still having issues running measurements.

I have also seen the issue of a measurement showing as **ongoing** even when it hasn't even started or has already finished.  I am new to Iris myself but I think the problem has to do with one of the following scenarios:

1. Not having a specific state for when the worker has assigned a measurement to an agent but the agent has not started it.  I think a state like "ready_to_run", "ready", or "waiting" would be much more clear than "ongoing".
2. The measurement has finished successfully but somehow the agent has failed to update the measurement's state .
3. Same as scenario 2 but the measurement has failed.

Can you cancel the measurement and try again?

Unfortunately, I am busy with other Iris-related work and do not currently have time to offer better support.  Perhaps @maxmouchet or @matthieugouel can provide deeper insight.

**Comment by SaiedKazemi** [comment]
@DD152 Per my previous comment about not having resources to provide support at the moment, I am closing this issue.  Once we have resources to provide support, we will let you know.
